### ISSUE TITLE
One Big Repo mode for dartdoc

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1671]
Dartdoc needs to work where there is one big repository holding all Dart code.  This meta-issue will track enhancements required to make this function.

- [ ]  #1609 - Allow running from Dart code.
- [x] #1659, #1661, #1662, #1665  - Refactor of Package/PackageGraph into LibraryContainer, Package, Category, and PackageGraph.  Necessary to be able to implement a new LibraryContainer for directories in the One Big Repo.
- [ ]  #739 -  Support for cross-linking between packages. 
- [ ] #1670 - Support "packages" that are single directories in a One Big Repo.

**Comment by sigurdm** [comment]
@jcollins-g is this still relevant?

**Comment by srawlins** [comment]
I do not think it still is.

**Comment by sigurdm** [comment]
Thanks @srawlins  Closing as obsolete
