### ISSUE TITLE
Release breaking changes 0.33.0 and 0.34.0

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#2339]
I have a few breaking changes which have landed, and a few pending, and I'd like to make smaller releases (and bumps), so these will be (at minimum) 0.33.0 and 0.34.0. @devoncarew also points out that #2337 needs to be carefully merged into the SDK, so I'm documenting the process for the next few releases:

1. [x] Import b039e21a7226b61ca2de7bd6c7a07fc77d4f64a9 internally (this was in-progress before #2337 landed).
2. [x] Bump the Dart SDK to b039e21a7226b61ca2de7bd6c7a07fc77d4f64a9.
3. [x] Import ab98003fc368f484fcc4c055770adea47bc83fbd (#2337) internally.
4. [x] Bump the Dart SDK to ab98003fc368f484fcc4c055770adea47bc83fbd, coordinated with @devoncarew .
5. [x] Cut 0.33.0 at ab98003fc368f484fcc4c055770adea47bc83fbd.
6. [x] Land new breaking changes like #2332.
7. [x] Import #2332 internally.
8. [x] Bump the Dart SDK including #2332.
9. [x] Cut 0.34.0 at the commit imported internally and in the Dart SDK.
